### ISSUE TITLE
15_live.t fails with latest Mozilla::CA

### ISSUE THREAD

**Issue by eserte** [andrewrjones/perl5-WWW-XBoxLive#2]
A sample fail report: http://www.cpantesters.org/cpan/report/f3c62c56-d273-11e4-bdf1-adbddfbfc7aa
The test suite seems to work fine with an older version of Mozilla::CA (i.e. ABH/Mozilla-CA-20130114.tar.gz).

Your module is not the only "victim". See https://github.com/gisle/mozilla-ca/pull/5 for a discussion of this problem.

**Comment by eserte** [comment]
It seems that this is not really a problem anymore (maybe with newer openssl versions being installed everywhere?). Therefore closing this issue.

**Comment by andrewrjones** [comment]
Thanks @eserte!
